### ISSUE TITLE
after glide get then go build error 

### ISSUE THREAD

**Issue by gstormlee** [shengdoushi/base58#1]
go version go1.10.1 darwin/amd64
glide version 0.13.1

glide.yaml:
package: .
import:
- package: github.com/shengdoushi/base58

go build error

**Comment by shengdoushi** [comment]
I try on glide on my mac, it works. Can you give the go build error below

My golang is 1.9,  I will install go 1.10 and try again

**Comment by shengdoushi** [comment]
go version go1.10.1 darwin/amd64
glide version 0.13.1

test works.

**Comment by shengdoushi** [comment]
I guess you copy the example from README.md. there was a type mistake: "baes58" should be "base58". I will fix it.
